CREATE LOGIN zz WITH PASSWORD = '123'
-- DROP LOGIN zz
USE Northwind
GO
CREATE USER zz FOR LOGIN zz
GO
EXEC sp_addrolemember 'db_owner', zz
GO
GRANT ALL PRIVILEGES ON ORDERS TO zz
GRANT SELECT, INSERT, UPDATE ON Orders TO zz
